// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptbktobsffhlbhjvinvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0Ymt0b2JzZmZobGJoanZpbnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTMxMDcsImV4cCI6MjA2Mzg2OTEwN30.0prZCq0n2y6HGL_JGeSMVZrpeswm_NpVwE0-WoW0R1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);